Выполнил домашнее задание №4
TuringClubMPEI/JavaCourse pull request #110
Opened 2024-04-24 18:59 UTC by noinvited

Выполнил домашнее задание №4

2024-04-24 20:45 UTC, lefasdayan requested changes

2024-04-24 20:45 UTC, lefasdayan commented on ru/turing/courses/lesson5/MyClass.java
> +public class MyClass {
Все-таки класс нужно называть конкретным именем, которое соответствует его специфике. Тут, наверное, Human

2024-04-24 20:45 UTC, lefasdayan commented on ru/turing/courses/lesson5/Sort.java
> + */
Респект за джавадок!

2024-04-24 20:45 UTC, lefasdayan commented on ru/turing/courses/lesson5/Sort.java
> +                            array[j + 1] = temp;
Одинаковые по сути действия, можно засунуть эти условия из двух if-ов в один с логическим или (||)

2024-04-26 09:24 UTC, noinvited commented on ru/turing/courses/lesson5/Sort.java
> +                            array[j + 1] = temp;
сделал все поправки в коммите: 103d7945d8b6f42e1e61429d10a0277192198efa

2024-04-26 20:17 UTC, lefasdayan approved these changes

2024-04-26 20:17 UTC, lefasdayan commented
Молодец!

2024-04-26 20:17 UTC, merged