fixed
TuringClubMPEI/JavaCourse pull request #31
Opened 2023-04-25 20:32 UTC by DmytriF

Sorry, what's late 
:):)
👍 💯 🔢 🥇 🥇

2023-04-25 21:19 UTC, Diagorn requested changes

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Registry.java
> +    public List removeByValue(T value) {
```suggestion
    public List<String> removeByValue(T value) {
```
Ты знаешь тип ключа, почему бы не указать его явно?

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Registry.java
> +                if (value.equals(entry.getValue())) {
В метод проверку на null вставить, если value == null оно тут упадёт

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Registry.java
> +            return storage.get(key).getRecord();
А почему возвращаем не само значение?

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Registry.java
> +        List<String> tempList = new ArrayList<>();
Опять же, почему не само значение а строковое представление?

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Registry.java
> +    public List getByName(String info) {
```suggestion
    public List<T> getByName(String info) {
```
Конкретизируй тип

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Registry.java
> +        boolean flag = true;
```suggestion
        boolean foundMatchingRecord = true;
```

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Registry.java
> +        int c = 1;
За такие имена переменных буду бить палкой по голове. Больно.

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Registry.java
> +        if (!storage.isEmpty()) {
Лучше инвертнуть условие.  
Если реестр пуст - написали в консоль - return; 
Дальше по коду после того, как это отработает, реестр гарантированно не пустой. И тогда уже можно выводить

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Homework3.java
> +        Scanner scanner =new Scanner(System.in);
Пробелы вокруг =

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Homework3.java
> +        int c;
Понятное имя для переменной

2023-04-25 21:19 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Homework3.java
> +                break;
Это всё через табуляцию для читабельности

2023-04-25 21:41 UTC, DmytriF commented on ru/turing/courses/lesson3/filippov/Registry.java
> +        int c = 1;
Ахахаххаха, постараюсь так не делать

2023-04-26 14:41 UTC, DmytriF commented on ru/turing/courses/lesson3/filippov/Record.java
> +    public abstract String getRecord();
Не знал, что такое есть 
сейчас сделаю

2023-04-26 15:03 UTC, DmytriF commented on ru/turing/courses/lesson3/filippov/Registry.java
> +        List<String> tempList = new ArrayList<>();
Я пробовал выводить объект, и он выводил, как я понял, ссылку, потом я написал метод toRecord(), теперь узнал про toString сейчас все будет

2023-04-26 15:28 UTC, Diagorn approved these changes
Молодец!

2023-04-26 15:28 UTC, Diagorn commented on ru/turing/courses/lesson3/filippov/Homework3.java
> +                    System.out.println("Вы вели что-то не то");
Мне кажется на тройку оно тоже это напишет, но окей, пусть так

2023-04-26 15:29 UTC, merged