add homework3
TuringClubMPEI/JavaCourse pull request #34
Opened 2023-04-30 15:29 UTC by Maylin7

2023-04-30 18:17 UTC, Diagorn requested changes

2023-04-30 18:17 UTC, Diagorn commented on ru/turing/courses/lesson3/Zheleznov/Homework3.java
> +        Car LadaPriora = new SportsCar(1, 200, 2);
Переменные с маленькой буквы, даже если имена собственные

2023-04-30 18:17 UTC, Diagorn commented on ru/turing/courses/lesson3/Zheleznov/Registry.java
> +            if (entry.getValue().equals(value)) {
Если entry.getValue() == null, то тут упадет, вставь проверку на это

2023-04-30 18:17 UTC, Diagorn commented on ru/turing/courses/lesson3/Zheleznov/Registry.java
> +    public void coutMaxSpeed() {
```suggestion
    public void printMaxSpeed() {
```
Термины из C давай не использовать

2023-04-30 18:17 UTC, Diagorn commented on ru/turing/courses/lesson3/Zheleznov/Suv.java
> +public class Suv extends Car {
А что такое Suv?

2023-04-30 18:20 UTC, Maylin7 commented on ru/turing/courses/lesson3/Zheleznov/Suv.java
> +public class Suv extends Car {
Внедорожник

2023-05-01 14:56 UTC, Diagorn requested changes

2023-05-02 13:33 UTC, Diagorn approved these changes
Молодец!

2023-05-02 13:33 UTC, merged