hw5 commit
TuringClubMPEI/JavaCourse pull request #41
Opened 2023-05-16 17:40 UTC by lefasdayan

2023-05-16 17:44 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/Animal.java
> +        if (this.name.length() > o.name.length()) {
Сюда проверку на null надо бы вставить

2023-05-16 17:45 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/Animal.java
> +        if (this.name.length() > o.name.length()) {
Да и не надо оно на самом деле. Просто проверил имя того и этого на null, если все ок, то вернул разницу длин строк

2023-05-16 17:46 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/Animal.java
> +        if (this.name.length() > o.name.length()) {
Только тогда еще проверить на равенство длин. Если равны - ничего не делать, если не равны - возвращать разницу

2023-05-16 17:46 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/Animal.java
> +        if (this.weightInKg > o.weightInKg) {
По аналогии с комментом про имя

2023-05-16 17:49 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/BubbleSorter.java
> +                    array[index - 1] = buffer;
У тебя одинаковый код и там и там, так и должно быть?

2023-05-16 18:59 UTC, lefasdayan commented on ru/turing/courses/lesson5/privalov/BubbleSorter.java
> +            for (int index = 1; index < array.length; index++) {
Так, перепроверил, тут всё правильно.

Step -- номер прохода, которых length-1
Index начинается с 1, т.к. проверяю текущий элемент с предыдущим, то есть array[1] c array[0], потом array[2] c array[1] и т.д. до последнего элемента

2023-05-16 23:18 UTC, Diagorn requested changes

2023-05-16 23:18 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/Animal.java
> +        if (this.name != null && o.name != null && this.name.length() > o.name.length()) {
А если `this.name.length() < o.name.length()`?
Давай результат сравнения выдавать все-таки если они просто различаются

2023-05-16 23:18 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/Animal.java
> +        if (this.id != null && o.id != null && this.id > o.id) {
По аналогии с комментом выше

2023-05-16 23:18 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/Animal.java
> +        if (this.weightInKg > o.weightInKg) {
По аналогии с комментом выше

2023-05-16 23:18 UTC, Diagorn commented on ru/turing/courses/lesson5/privalov/BubbleSorter.java
> +            for (int index = 1; index < array.length; index++) {
С такой реализацией у тебя просто появляются лишние проходы цикла. Это будет работать, но не оптимально. Почитай про пузырьковую сортировку и ее реализации

2023-05-17 12:42 UTC, Diagorn approved these changes
Молодец!

2023-05-17 12:42 UTC, merged