Homework4
TuringClubMPEI/JavaCourse pull request #42
Opened 2023-05-16 18:06 UTC by DmytriF

Извиняюсь за задержку домашки, постараюсь так не делать

2023-05-16 23:12 UTC, Diagorn requested changes

2023-05-16 23:12 UTC, Diagorn commented on ru/turing/courses/lesson4/filippov/NotFoundError.java
> +public class NotFoundError extends RuntimeException {
Лучше переделать на
```suggestion
public class NotFoundException extends RuntimeException {
```
Error - это все-таки то, что мы не можем отловить

2023-05-16 23:12 UTC, Diagorn commented on ru/turing/courses/lesson4/filippov/NotFoundError.java
> +        return "Такого enum нет";
Есть встроенный конструктор с полем message, попробуй переделать на него

2023-05-18 19:21 UTC, Diagorn requested changes

2023-05-18 19:21 UTC, Diagorn commented on ru/turing/courses/lesson4/filippov/NotFoundException.java
> +        this.name = name;
Зачем городить огород с `@Override getMessage?`? Просто в этой строчке `this.message = name`

2023-05-18 19:21 UTC, Diagorn commented on ru/turing/courses/lesson4/filippov/NotFoundException.java
> +        this.name = name;
Или, кстати, `super(name);`, оно так тоже скушает

2023-05-21 14:58 UTC, Volga21 commented
ой, сори, сюда 5 домашку закинул

2023-05-21 15:00 UTC, Volga21 commented
Оставить здесь или удалить ?

2023-05-22 06:36 UTC, Diagorn requested changes

2023-05-22 06:37 UTC, Diagorn commented
> Оставить здесь или удалить ?

Ладно, пускай будет

2023-07-11 17:45 UTC, Diagorn approved these changes
Молодец!

2023-07-11 17:45 UTC, merged