Shipkov hw2
TuringClubMPEI/JavaCourse pull request #61
Opened 2023-11-15 20:05 UTC by damatvey

- Выполнил дз1
- Выполнил дз2

2023-11-16 16:56 UTC, lefasdayan requested changes

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/Homework2.java
> +        //подключаю библиотеку и создаю переменную с текущим годом
А как же разбить это все на три отдельных метода?

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/Homework2.java
> +        String strana = scan.next();
Лучше называть переменные везде на английском

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Animal.java
> +    protected int numberOfPaws;
Лучше перенести наверх к остальным полям

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Cat.java
> +
А реализация?

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Cat.java
> +
Реализация?)

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Mouse.java
> +
Реализация(

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Mouse.java
> +
РеАлИзАцИя

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Mouse.java
> +        System.out.println("Мыш......(кродеться)...");
хехе

2023-11-16 16:56 UTC, lefasdayan commented on ru/turing/courses/lesson2/Homework2.java
> +
Было бы неплохо добавить в Main реализацию животных и их методов

2023-11-19 15:47 UTC, Diagorn commented on ru/turing/courses/lesson2/animals/Mouse.java
> +        System.out.println("Мыш......(кродеться)...");
Хехе

2023-11-19 16:04 UTC, lefasdayan requested changes

2023-11-19 16:04 UTC, lefasdayan commented on ru/turing/courses/lesson2/Homework2.java
> +        kvartira = kvartira.replace(String.valueOf(charToRemove), "");
Внутреннюю логику методов надо засунуть в сами тела методов. В мэйне -- только вызывать методы

2023-11-19 16:04 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Animal.java
> +    protected String klichka;
```suggestion
    protected String nickname;
```
Называть по возможности словами на английском языке!

2023-12-01 19:58 UTC, lefasdayan requested changes

2023-12-01 19:58 UTC, lefasdayan commented on ru/turing/courses/lesson2/Homework2.java
> +        int currentYear = calendar.get(Calendar.YEAR);
Это всё можно засунуть внутрь метода

2023-12-01 19:58 UTC, lefasdayan commented on ru/turing/courses/lesson2/Homework2.java
> +        String strana = scan.next();
!

2023-12-01 19:58 UTC, lefasdayan commented on ru/turing/courses/lesson2/Homework2.java
> +        String gorodBuffer = scan.next();
```suggestion
        String cityBuffer = scan.next();
```
И дальше тоже исправь

2023-12-01 19:58 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Animal.java
> +    protected String klichka;
!

2023-12-01 19:58 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Animal.java
> +    public String getKlichka() {
Соответственно с названием полей переименовать геттеры/сеттеры и конструкторы в наследниках

2023-12-01 19:58 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Cat.java
> +    public void play(String playWithLaser) {
```suggestion
    @Override
    public void play(String playWithLaser) {
```
И эту же аннотацию над всеми переопределенными от родителя методами

2023-12-02 11:14 UTC, lefasdayan commented
Еееее бойййййй 🥇

2023-12-02 11:14 UTC, merged