Alekseev
TuringClubMPEI/JavaCourse pull request #71
Opened 2023-11-17 11:37 UTC by omgNick0

- Добавил в Solution.java(lesson 2) создание юзера + вызов метода у объектов класса Dog, Cat.
- Подправил названия переменных по camelCase

2023-11-17 12:17 UTC, lefasdayan requested changes

2023-11-17 12:17 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Cat.java
> +    public Cat(String name, int age) {this.name = name; this.age = age;}
Всё ещё нет полей из Animal :)

2023-11-17 12:17 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Dog.java
> +    private boolean owner_missing; // 1 or 0
```suggestion
    private boolean ownerMissing; // 1 or 0
```
CamelCase во везде!

2023-11-17 12:17 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Dog.java
> +    public Dog(String name, int age) {this.name = name; this.age = age;}
Тоже нет super полей из Animal

2023-11-17 12:17 UTC, lefasdayan commented on ru/turing/courses/lesson2/Solution.java
> +        User leviAkkerman = new User("Levi Akkerman");
Поздравляю с окончанием AOT!

2023-11-19 15:48 UTC, Diagorn commented on ru/turing/courses/lesson2/Solution.java
> +        User leviAkkerman = new User("Levi Akkerman");
Ура!

2023-11-19 15:49 UTC, Diagorn commented on ru/turing/courses/lesson2/User.java
> +        String[] dates = birth.split("\\."); // мне это idea предложила вместо "." , не знаю почему
Потому что `split()` внутрь себя берёт регулярку, в которой точка - любой символ. При желании почитай про регулярки, их мы трогать не будем, но знать, что это такое - полезно

2023-11-19 15:50 UTC, Diagorn commented
Не коммить файлы .class

2023-11-19 16:41 UTC, lefasdayan requested changes

2023-11-19 16:41 UTC, lefasdayan commented on ru/turing/courses/lesson2/animals/Cat.java
> +    public void cath_mouse() {
```suggestion
    public void catchMouse() {
```

2023-11-19 16:42 UTC, merged

2023-11-19 16:42 UTC, lefasdayan commented
Молодец!!!