HW 4
TuringClubMPEI/JavaCourse pull request #96
Opened 2023-12-03 17:30 UTC by OronStor

- Registry class
- user class & abstract user class
- hw methods for registry
- additional method
- JavaDoc

2023-12-04 18:29 UTC, lefasdayan requested changes

2023-12-04 18:29 UTC, lefasdayan commented on ru/turing/courses/lesson3/Registry.java
> +    public List<String> removeByValue(String value) {
Так-так-так, removeByValue() принимает на вход именно объект. В твоем случае на вход пойдет тип Т, то есть в solution'e это будет User. Не стринг!

2023-12-04 18:29 UTC, lefasdayan commented on ru/turing/courses/lesson3/Registry.java
> +            if (entry.getValue().equals(name)) {
```suggestion
            if (entry.getValue().getName().equals(name)) {
```
Получаем именно по имени, а имя лежит внутри value.

2023-12-07 05:59 UTC, OronStor commented on ru/turing/courses/lesson3/Registry.java
> +            if (entry.getValue().equals(name)) {
Реализация User`а : 
@Override
    public String getValue() {
        return name;
    }
Исправлю название для читаемости

2023-12-09 17:32 UTC, lefasdayan commented on ru/turing/courses/lesson3/Registry.java
> +    public List<String> removeByValue(T User) {
```suggestion
    public List<String> removeByValue(T user) {
```
T -- это тип, после него следует название объекта, а оно с маленькой буквы

2023-12-09 17:35 UTC, lefasdayan commented on ru/turing/courses/lesson3/Registry.java
> +    public List<String> removeByValue(T User) {
```suggestion
    public List<String> removeByValue(T user) {
```
T -- это тип, после него следует название объекта, а оно с маленькой буквы

2023-12-09 17:36 UTC, merged

2023-12-09 17:36 UTC, lefasdayan commented
Молодец! Отличная домашка